### ISSUE TITLE
Parsing issue (I think)

### ISSUE THREAD

**Issue by hmsnaith** [mgifos/quick-plan#11]
This code is just what I need - but I’m having trouble parsing. I can get the sample 80k ultra csv
[Bike.zip](https://github.com/mgifos/quick-plan/files/2035698/Bike.zip)

 to parse and load, but my own csv files give errors. I suspect this MAY be an issue with unix (actually Mac OS X) vs Windows newline / eol characters, but hoped you might be able to shed some light.
When trying to schedule the attached csv file 
The error is 👍 

Exception in thread "main" java.lang.IllegalArgumentException: Duration step type was expected, bike
        at com.github.mgifos.workouts.model.Step$.parseDurationStep(Step.scala:76)
        at com.github.mgifos.workouts.model.Step$.parse(Step.scala:66)
        at com.github.mgifos.workouts.model.Workout$.loop$1(Workout.scala:42)
        at com.github.mgifos.workouts.model.Workout$.parseDef(Workout.scala:48)
        at com.github.mgifos.workouts.model.WeeklyPlan.$anonfun$processed$4(WeeklyPlan.scala:16)
        at scala.Option.map(Option.scala:146)
        at com.github.mgifos.workouts.model.WeeklyPlan.$anonfun$processed$1(WeeklyPlan.scala:15)
        at com.github.mgifos.workouts.model.WeeklyPlan.$anonfun$processed$1$adapted(WeeklyPlan.scala:13)
        at scala.collection.generic.GenTraversableFactory.tabulate(GenTraversableFactory.scala:148)
        at com.github.mgifos.workouts.model.WeeklyPlan.weekPlan$1(WeeklyPlan.scala:13)
        at com.github.mgifos.workouts.model.WeeklyPlan.loop$1(WeeklyPlan.scala:25)
        at com.github.mgifos.workouts.model.WeeklyPlan.processed$lzycompute(WeeklyPlan.scala:28)
        at com.github.mgifos.workouts.model.WeeklyPlan.processed(WeeklyPlan.scala:11)
        at com.github.mgifos.workouts.model.WeeklyPlan.workouts(WeeklyPlan.scala:34)
        at com.github.mgifos.workouts.Main$.run(Main.scala:117)
        at com.github.mgifos.workouts.Main$.delayedEndpoint$com$github$mgifos$workouts$Main$1(Main.scala:43)
        at com.github.mgifos.workouts.Main$delayedInit$body.apply(Main.scala:32)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at com.github.mgifos.workouts.Main$.main(Main.scala:32)
        at com.github.mgifos.workouts.Main.main(Main.scala)

**Comment by mgifos** [comment]
I think the problem was colon character ":" in your workout name. I recently increased the number of characters that can be used in workout names. Can you try to import it again with the latest release 0.2.2?

https://github.com/mgifos/quick-plan/releases

Please let me know about your findings.

**Comment by hmsnaith** [comment]
Sorry - I still get the same error.
I should have said, I've already tried without the ":" (I suspected that too)
I just tried importing after converting to DOS linefeeds (using perl command from https://stackoverflow.com/questions/6373888/converting-newline-formatting-from-mac-to-windows?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) and I don't get the error any more.
I still don't get the workouts imported, but I'm getting closer

**Comment by hmsnaith** [comment]
It was definitely the line feeds issue - now successfully imported my run schedule
Great tool!
I really the issue above was (at least partially) because I was trying to create a ****bike**** schedule and it doesn't recognise 'bike' as the step type!
Have to add that as a feature request now

**Comment by mystygage** [comment]
That’s strange. I also use a Mac and successfully imported a file with LF line endings.

**Comment by hmsnaith** [comment]
happy for you to close this issue - thanks
