### ISSUE TITLE
Change request - minutes with up to 3 digits

### ISSUE THREAD

**Issue by f4hla** [mgifos/quick-plan#23]
can <minute> be changed from \d{1,2} to \d{1,3} to handle trainings above 1h40?
Thanks

**Comment by mgifos** [comment]
That's actually already supported, please refer to the ultra marathon sample provides as a Google spreadsheet link at the main page. It contains runs even of 4-5h. E.g. "225:00". So related to this issue we only need to update a documentation a bit.

**Comment by f4hla** [comment]
Actually, I did that report because I got the following error message (both Mac and Windows) using 0.2.3
Your opinion?

---
Exception in thread "main" java.lang.IllegalArgumentException: Duration cannot be parsed 120
	at com.github.mgifos.workouts.model.Duration$.parse(Duration.scala:65)
	at com.github.mgifos.workouts.model.Step$.expect(Step.scala:84)
	at com.github.mgifos.workouts.model.Step$.parseDurationStep(Step.scala:73)
	at com.github.mgifos.workouts.model.Step$.parse(Step.scala:66)
	at com.github.mgifos.workouts.model.Workout$.loop$1(Workout.scala:43)
	at com.github.mgifos.workouts.model.Workout$.parseDef(Workout.scala:49)
	at com.github.mgifos.workouts.model.WeeklyPlan.$anonfun$processed$4(WeeklyPlan.scala:16)
	at scala.Option.map(Option.scala:146)
	at com.github.mgifos.workouts.model.WeeklyPlan.$anonfun$processed$1(WeeklyPlan.scala:15)
	at com.github.mgifos.workouts.model.WeeklyPlan.$anonfun$processed$1$adapted(WeeklyPlan.scala:13)
	at scala.collection.generic.GenTraversableFactory.tabulate(GenTraversableFactory.scala:148)
	at com.github.mgifos.workouts.model.WeeklyPlan.weekPlan$1(WeeklyPlan.scala:13)
	at com.github.mgifos.workouts.model.WeeklyPlan.loop$1(WeeklyPlan.scala:25)
	at com.github.mgifos.workouts.model.WeeklyPlan.processed$lzycompute(WeeklyPlan.scala:28)
	at com.github.mgifos.workouts.model.WeeklyPlan.processed(WeeklyPlan.scala:11)
	at com.github.mgifos.workouts.model.WeeklyPlan.workouts(WeeklyPlan.scala:34)
	at com.github.mgifos.workouts.Main$.run(Main.scala:117)
	at com.github.mgifos.workouts.Main$.delayedEndpoint$com$github$mgifos$workouts$Main$1(Main.scala:43)
	at com.github.mgifos.workouts.Main$delayedInit$body.apply(Main.scala:32)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.github.mgifos.workouts.Main$.main(Main.scala:32)
	at com.github.mgifos.workouts.Main.main(Main.scala)

**Comment by mgifos** [comment]
Release in v0.2.4
