### ISSUE TITLE
cannot create workout

### ISSUE THREAD

**Issue by sdaigl** [mgifos/quick-plan#28]
Good day,
I have a problem running the tool
I tried with mac  (osx)and also with win7 (using java8 jdk) same error in both case, tried with same spreadsheet ultra-80 found on google calendar, same bug, I must be missing something or mabe my java version is not right, I also installed version 8 and the latest, and same response

MacBook-Pro-de-Serge-2:bin segi$ java --version
openjdk 11 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
MacBook-Pro-de-Serge-2:bin segi$ 

here is my output:
MacBook-Pro-de-Serge-2:bin segi$ ./quick-plan schedule -n 2018-10-15  -e sdaigl@gmail.com 1.csv
Password: 
[WARN] [10/08/2018 19:50:40.913] [quick-plan-akka.actor.default-dispatcher-17] [akka.actor.ActorSystemImpl(quick-plan)] Illegal header: Illegal 'expires' header: Illegal weekday in date 1997-07-26T05:00:00: is 'Mon' but should be 'Sat'
Successfully logged in to Garmin Connect

Creating workouts:
Logged out and closed connection
Exception in thread "main" java.util.concurrent.ExecutionException: Boxed Error
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:83)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:75)
	at scala.concurrent.impl.Promise$KeptPromise$.apply(Promise.scala:402)
	at scala.concurrent.Promise$.fromTry(Promise.scala:138)
	at scala.concurrent.Promise$.failed(Promise.scala:124)
	at scala.concurrent.Future$.failed(Future.scala:620)
	at com.github.mgifos.workouts.GarminConnect.$anonfun$createWorkouts$4(GarminConnect.scala:71)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.Error: Cannot create workout
	... 15 more

**Comment by sdaigl** [comment]
It works now, I am not sure what was the problem, but I Have it working
thanks!

**Comment by mgifos** [comment]
Sometimes the server just doesn't work correctly - that could be the possible cause.

**Comment by sdaigl** [comment]
I did noticed that, by the way great tool, works perfectly and does really save time. Good work !!!
