### ISSUE TITLE
Cant schedule workouts - Exception in thread "main" java.util.concurrent.ExecutionException: Boxed Error

### ISSUE THREAD

**Issue by pschonmann** [mgifos/quick-plan#35]
Hi, im trying use your program to schedule some training plan. Just copy & paste example from this page ( 2w plan ) into Libre office and save as CSV ( added as attachment ) giving me that result.

```
d:\DOWNLOAD\quick-plan-0.3.1\bin>quick-plan.bat schedule -s 2018-12-01 -e pschonmann TEST.csv

[WARN] [11/29/2018 23:01:34.631] [quick-plan-akka.actor.default-dispatcher-5] [akka.actor.ActorSystemImpl(quick-plan)] Illegal header: Illegal 'expires' header: Illegal weekday in date 1997-07-26T05:00:00: is 'Mon' but should be 'Sat'

Creating workouts:
Successfully logged in to Garmin Connect
Logged out and closed connection
Exception in thread "main" java.util.concurrent.ExecutionException: Boxed Error
        at scala.concurrent.impl.Promise$.resolver(Promise.scala:83)
        at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:75)
        at scala.concurrent.impl.Promise$KeptPromise$.apply(Promise.scala:402)
        at scala.concurrent.Promise$.fromTry(Promise.scala:138)
        at scala.concurrent.Promise$.failed(Promise.scala:124)
        at scala.concurrent.Future$.failed(Future.scala:620)
        at com.github.mgifos.workouts.GarminConnect.$anonfun$createWorkouts$4(GarminConnect.scala:71)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.Error: Cannot create workout
        ... 15 more
```
[TEST.zip](https://github.com/mgifos/quick-plan/files/2631051/TEST.zip)

**Comment by pschonmann** [comment]
Oh, worked! Seems account was locked :(

**Comment by mgifos** [comment]
I managed to reproduce it by using my username instead of my email address. I'll close this issue,  but some validation could be handy here in the future.
