### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/github/mgifos/workouts/Main : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by marco-ostaska** [mgifos/quick-plan#5]
Hi,
I read your post in https://forums.garmin.com/forum/on-the-trail/wrist-worn/fenix-3-hr/145908- and I really liked the idea, but I could not run it here.

I don't know java or scala, and to be honest I did  not really read all the bash code. Not sure if should work with OSX or just linux/windows, but trying to run it in osx I got the error:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/github/mgifos/workouts/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```
I believe it has something to do with this part:
`declare -a app_mainclass=(com.github.mgifos.workouts.Main)`

my java version:
```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
```

Again, I really like the idea. thanks for sharing it.

**Comment by mgifos** [comment]
Your version of Java is too old, please install new Java and try again. The prerequisite is Java 7 as installation guide states: https://java.com/en/download/
