### ISSUE TITLE
Check 1,2 is this thing still on?

### ISSUE THREAD

**Issue by octomike** [mgifos/quick-plan#58]
I was just trying out this project and (after downgrading to JDK8), I get:

```
./quick-plan schedule -e mk-garmin@galax.is -n 2021-07-26 -x ~/Downloads/marathon-345.csv 
Password: 
Successfully logged in to Garmin Connect!
Exception in thread "main" java.util.concurrent.ExecutionException: Boxed Error
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:87)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
	at scala.concurrent.impl.Promise$KeptPromise$.apply(Promise.scala:406)
	at scala.concurrent.Promise$.fromTry(Promise.scala:142)
	at scala.concurrent.Promise$.failed(Promise.scala:128)
	at scala.concurrent.Future$.failed(Future.scala:623)
	at com.github.mgifos.workouts.GarminConnect.$anonfun$getWorkoutsMap$1(GarminConnect.scala:158)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.Error: Cannot retrieve workout list from Garmin Connect
```

Does that mean the project hasn't caught up with changes in Garmin Connect?

**Comment by mgifos** [comment]
It should be resolved with version 0.5.1
