### ISSUE TITLE
Get error trying to execute ( java.lang.Error: Cannot create workout)

### ISSUE THREAD

**Issue by chipbite** [mgifos/quick-plan#59]
Hi, just testing this today. 
It says **Successfully logged in to Garmin Connect!**
But then I get an error.
I get the following error:
```lang:bash
$ quick-plan import -e chipbite -p <MY PASSWORD HERE> oneweek-test.csv                                                                                                                  
Creating workouts:
Successfully logged in to Garmin Connect!
Exception in thread "main" java.util.concurrent.ExecutionException: Boxed Error
        at scala.concurrent.impl.Promise$.resolver(Promise.scala:87)
        at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
        at scala.concurrent.impl.Promise$KeptPromise$.apply(Promise.scala:406)
        at scala.concurrent.Promise$.fromTry(Promise.scala:142)
        at scala.concurrent.Promise$.failed(Promise.scala:128)
        at scala.concurrent.Future$.failed(Future.scala:623)
        at com.github.mgifos.workouts.GarminConnect.$anonfun$createWorkouts$3(GarminConnect.scala:67)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.Error: Cannot create workout
        ... 15 more

```

BR! /marcus

**Comment by chipbite** [comment]
OK, checked the code and AFAICS its not supported, only bicycling type is supported currently. 

https://github.com/mkuthan/garmin-workouts/blob/master/garminworkouts/models/workout.py#L14

https://github.com/mkuthan/garmin-workouts/blob/master/garminworkouts/models/workout.py#L40


Closing this for now.
BR! /marcus

**Comment by chipbite** [comment]
I tried this again, and now I cant get it to logon to garmin connect either. 
Maybe something has changed with the logon to garmin connect.

I now get:

```
Login was not successful, check your username and password and try again.
Bye
```

There seems to be no log or verbose option.
BR! /marcus

**Comment by mgifos** [comment]
Indeed, something was changed - version v0.5.1 should solve this.
